# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - main

pool:
  name: 4ISADO

resources:
  - repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        steps:
          - task: Docker@2
            displayName: Build and Push Image
            inputs:
              containerRegistry: 'Docker Hub - 4lch4'
              repository: 'Ansel'
              command: 'buildAndPush'
              tags: |
                $(Build.BuildId)
                latest
