trigger:
- master

pool:
  name: 'ROSA-ADO'

steps:
- task: Docker@2
  displayName: Build and Push the alcha/ansel Docker image.
  inputs:
    containerRegistry: 'Docker Hub Registry'
    repository: 'alcha/ansel'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: |
      latest