# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - main

pool:
  name: 4ISADO

resources:
  - repo: self

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        steps:
          # - task: Bash@3
          #   displayName: Build and Push Image
          #   inputs:
          #     targetType: 'inline'
          #     script: |
          #       docker build -t 4lch4/ansel:latest -4lch4/ansel:$(Build.BuildId) .
          #       docker push 4lch4/ansel -a

          - task: Docker@2
            displayName: Build and Push Image
            inputs:
              containerRegistry: 'Docker Hub - 4lch4'
              repository: '4lch4/ansel'
              command: 'buildAndPush'
              tags: |
                $(Build.BuildId)
                latest
          - task: Bash@3
            displayName: Task Cleanup
            inputs:
              targetType: 'inline'
              script: 'rm -rf $(Build.SourcesDirectory)'
