# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - main

pool:
  name: 4ISADO

resources:
  - repo: self

variables:
  - name: 'AppVersion'
    value: '0.3.1'

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build and Push
        steps:
          - task: Docker@2
            displayName: Build and Push Image
            inputs:
              containerRegistry: 'Docker Hub - 4lch4'
              repository: '4lch4/ansel'
              command: 'buildAndPush'
              tags: |
                $(Build.BuildId)
                $(AppVersion)
                latest
          - task: PublishPipelineArtifact@1
            displayName: Publish Manifest
            inputs:
              targetPath: '$(Build.SourcesDirectory)/manifest.yml'
              artifact: 'manifest'
              publishLocation: 'pipeline'

      - job: StatusReport
        displayName: Status Report
        dependsOn: 'Build'
        pool: server
        steps:
          - task: InvokeRESTAPI@1
            inputs:
              connectionType: 'connectedServiceName'
              serviceConnection: 'Discord Webhook Channel'
              method: 'POST'
              body: |
                {
                  "content": "$(Build.BuildId) ⸺ $AGENT_JOBSTATUS",
                  "username": "4ISADO"
                }
