# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - main

pool:
  name: 4ISADO

resources:
  - repo: self

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build and Push
        steps:
          - task: Docker@2
            displayName: Build and Push Image
            inputs:
              containerRegistry: 'Docker Hub - 4lch4'
              repository: '4lch4/ansel'
              command: 'buildAndPush'
              tags: |
                $(Build.BuildId)
                latest
          - task: Bash@3
            displayName: Task Cleanup
            inputs:
              targetType: 'inline'
              script: 'rm -rf $(Build.SourcesDirectory)'

          - task: InvokeRESTAPI@1
            inputs:
              connectionType: 'connectedServiceName'
              serviceConnection: 'Discord Webhook Channel'
              method: 'POST'
              body: |
                {
                  "content": "$(Build.BuildId) ⸺ $(Agent.JobStatus)!",
                  "username": "4ISADO"
                }
              waitForCompletion: 'false'
