version: 3

tasks:
  build:
    desc: Builds the project by transpiling the codebase into JavaScript.
    aliases:
      - bd
    cmds:
      - go build -o bin/ansel ./...

  push:
    desc: Push any git changes and tags to the remote repository.
    aliases:
      - gp
    deps:
      - build
    cmds:
      - git push
      - git push --tags

  run:
    cmds:
      - air -c .air.toml
