apiVersion: apps/v1
kind: Deployment
metadata:
  name: ansel
  namespace: ansel
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ansel
  template:
    metadata:
      labels:
        app: ansel
    spec:
      containers:
      - name: ansel
        image: 4lch4/ansel:latest
        ports:
        - containerPort: 4242
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: do-secrets
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: do-secrets
              key: AWS_SECRET_ACCESS_KEY
        livenessProbe:
          httpGet:
            path: /healthz
            port: 4242
          initialDelaySeconds: 25
        readinessProbe:
          httpGet:
            path: /healthz
            port: 4242
          initialDelaySeconds: 25
        # resources:
        #   requests:
        #     cpu: "50m"
        #     memory: "256Mi"
        #   limits: 
        #     cpu: "100m"
        #     memory: "512Mi"